# Streamlit Session State Keys
NCBI_SUMMARY_FORM = "NCBI_SUMMARY_FORM"
NCBI_DF = "NCBI_DF"
NCBI_DF_FILTER = "NCBI_DF_FILTER"

# Streamlit UI
PAGE_LAYOUT = "wide"
MAIN_PAGE_COLS_SIZE = [0.8, 0.2]
MAIN_PAGE_COLS_GAP = "small"
TOP_N_ORGANISMS = 15
